import type { NextPage } from "next";
import Head from "next/head";
import { gql } from "apollo-server-micro";

export const graphql = gql`
  query HomeQuery($id: ID!) {
    user(id: $id) {
      id
    }
  }
`;

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    Test
  </div>
);

export default Home;
